// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2380602555_LeNgocQuangVinh_KTGiuaKy.Models;

#nullable disable

namespace _2380602555_LeNgocQuangVinh_KTGiuaKy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.ChiTietDangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .HasColumnType("int");

                    b.Property<string>("MaHP")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("MaDK", "MaHP");

                    b.HasIndex("MaHP");

                    b.ToTable("ChiTietDangKies");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDK"));

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayDK")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDK");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKies");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHP")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHP");

                    b.ToTable("HocPhans");

                    b.HasData(
                        new
                        {
                            MaHP = "CNTT01",
                            SoLuong = 99,
                            SoTinChi = 3,
                            TenHP = "Lập trình C"
                        },
                        new
                        {
                            MaHP = "CNTT02",
                            SoLuong = 99,
                            SoTinChi = 2,
                            TenHP = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            MaHP = "QTKD01",
                            SoLuong = 100,
                            SoTinChi = 2,
                            TenHP = "Kinh tế vi mô"
                        },
                        new
                        {
                            MaHP = "QTDK02",
                            SoLuong = 99,
                            SoTinChi = 3,
                            TenHP = "Xác suất thống kê 1"
                        });
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNganh");

                    b.ToTable("NganhHocs");

                    b.HasData(
                        new
                        {
                            MaNganh = "CNTT",
                            TenNganh = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaNganh = "QTKD",
                            TenNganh = "Quản trị kinh doanh"
                        });
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSV");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSV = "2380602555",
                            GioiTinh = "Nam",
                            Hinh = "/Content/images/sv1.jpg",
                            HoTen = "Lê Ngọc Quang Vinh",
                            MaNganh = "CNTT",
                            NgaySinh = new DateTime(2005, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.ChiTietDangKy", b =>
                {
                    b.HasOne("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.DangKy", "DangKy")
                        .WithMany("ChiTietDangKies")
                        .HasForeignKey("MaDK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.HocPhan", "HocPhan")
                        .WithMany("ChiTietDangKies")
                        .HasForeignKey("MaHP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.DangKy", b =>
                {
                    b.HasOne("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.SinhVien", "SinhVien")
                        .WithMany("DangKies")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.SinhVien", b =>
                {
                    b.HasOne("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.NganhHoc", "NganhHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.DangKy", b =>
                {
                    b.Navigation("ChiTietDangKies");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.HocPhan", b =>
                {
                    b.Navigation("ChiTietDangKies");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("_2380602555_LeNgocQuangVinh_KTGiuaKy.Models.SinhVien", b =>
                {
                    b.Navigation("DangKies");
                });
#pragma warning restore 612, 618
        }
    }
}
